version: '3.8'

services:
  db: 
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB="go_gram_db" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  app:
    build: .
    container_name: go-app
    environment:
      - DB_NAME=go_gram_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db # refer to db service in the upper
    depends_on:
      - db
    ports:
      - "3000:3000"  # Map port 3000 on the host to port 3000 in the container


volumes:
  postgres_data: